import Head from "next/head";

type propsType = {
    title: string;
};

export default function Header(props: propsType) {
    const { title = "Create Next App" } = props;

    return (
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
}
