
import Head from "next/head";
import Image from "next/image";
import styles from "../page.module.css";

export default function SSRPage() {
  
  const imgTitle = "新疆库俄铁路"

  const imgUrl =  "https://p0.meituan.net/scarlett/436ab52281f3f5033f77a48f5c12bd671009047.jpg"
  
  return (
    <div className={styles.container}>
      <Head>
        <title>CSR测试页面</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          CSR <p>前端渲染</p>
        </h1>

        <p className={styles.description}>
          <code className={styles.code}>
            请求接口，并把返回的数据传递给组件去渲染
          </code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>{imgTitle} &rarr;</h2>
            <Image src={imgUrl} alt={imgTitle} width={256} height={171} />
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};


